#pragma once

#define DISPLAY_QUADRANT_TOP    0
#define DISPLAY_QUADRANT_RIGHT  1
#define DISPLAY_QUADRANT_BOTTOM 2
#define DISPLAY_QUADRANT_LEFT   3
#define NUM_DISPLAY_QUADRANTS   4

#define NUM_KEYS 256

#define MAX_VIEWPORT_WIDTH 2048
#define MAX_VIEWPORT_HEIGHT 2048
